services:
  avior-nuxt:
    image: ghcr.io/spiritreader/avior-nuxt:${TAG:-latest}
    container_name: avior-nuxt
    ports:
      - "${PORT:-10010}:10009"
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://MongoDB:27017/Avior}
    restart: unless-stopped
    networks:
      - local
    labels:
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/Spiritreader/avior-nuxt/2208c03bc591082d4a491c9f91c98f82b88fcf40/public/dryicons_love_file_icon_6200.png"
      - "net.unraid.docker.webui=http://[IP]:[PORT:10009]/"

networks:
  local:
    external: true
