services:
  avior-nuxt:
    image: ghcr.io/spiritreader/avior-nuxt:${TAG:-latest}
    ports:
      - "${PORT:-10010}:10009"
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://MongoDB:27017/Avior}
    restart: unless-stopped
    networks:
      - local
    labels:
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/spiritreader/avior-nuxt/master/static/dryicons_love_file_icon_6200.png"
      - "net.unraid.docker.webui=http://[IP]:[PORT:10009]/"

networks:
  local:
    external: true
